import { useEffect, useState } from "react";

import { PageHeader } from "../../components/common/PageHeader";
import { useUnreadSummary } from "../../context/UnreadSummaryContext";
import { api } from "../../lib/api";
import { getApiErrorMessage } from "../../lib/getApiErrorMessage";

type Notification = {
  id: number;
  category: string;
  title: string;
  message: string;
  isRead: boolean;
  createdAt: string;
};

export function NotificationsPage() {
  const { refreshSummary } = useUnreadSummary();
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [error, setError] = useState("");

  async function loadNotifications() {
    try {
      const response = await api.get<Notification[]>("/notifications");
      setNotifications(response.data);
    } catch (submissionError) {
      setError(getApiErrorMessage(submissionError, "Unable to load notifications."));
    }
  }

  useEffect(() => {
    async function initializeNotificationsPage() {
      try {
        await api.patch("/notifications/read-all");
      } catch {
        // Keep loading the page even if automatic read sync fails.
      }

      await loadNotifications();
      await refreshSummary();
    }

    void initializeNotificationsPage();
  }, [refreshSummary]);

  async function markRead(notificationId: number) {
    setError("");
    try {
      await api.patch(`/notifications/${notificationId}/read`);
      await loadNotifications();
      await refreshSummary();
    } catch (submissionError) {
      setError(getApiErrorMessage(submissionError, "Unable to update notification."));
    }
  }

  return (
    <div>
      <PageHeader
        eyebrow="Notifications"
        title="Alerts and reminders"
        description="Track warnings, recognition notices, and evaluation-related alerts generated by the system."
      />

      {error ? <p className="mb-4 text-sm text-rose-600">{error}</p> : null}

      <div className="space-y-4">
        {notifications.map((item) => (
          <article className="panel p-6" key={item.id}>
            <div className="flex items-start justify-between gap-4">
              <div>
                <h2 className="text-lg font-semibold text-slate-950">{item.title}</h2>
                <p className="mt-2 text-sm leading-6 text-slate-500">{item.message}</p>
              </div>
              <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-slate-700">
                {item.isRead ? "Read" : "Unread"}
              </span>
            </div>
            <p className="mt-4 text-xs uppercase tracking-[0.2em] text-slate-400">{item.createdAt}</p>
            {!item.isRead ? (
              <button className="btn-secondary mt-4" onClick={() => void markRead(item.id)} type="button">
                Mark as read
              </button>
            ) : null}
          </article>
        ))}
      </div>
    </div>
  );
}
